name: Tests
env:
  OX_AR_DB_USER: postgres
  OX_AR_TEST_DB: ci_test
  OX_AR_DB_PASS: postgres
  RAILS_ENV: test

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: ${{ env.OX_AR_DB_USER }}
          POSTGRES_DB: ${{ env.OX_AR_TEST_DB }}
          POSTGRES_PASSWORD: ${{ env.OX_AR_DB_PASS }}
    strategy:
      matrix:
        RAILS_VERSION:
          - 6.1.1
          - 7.0.8
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.RAILS_VERSION }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.RAILS_VERSION }}-gems-
      - name: Setup
        env:
          RAILS_VERSION: ${{ matrix.RAILS_VERSION }}
        run: |
          bundle install
          bundle exec rake --trace db:create db:schema:load db:seed
      - name: Test
        env:
          RAILS_VERSION: ${{ matrix.RAILS_VERSION }}
        run: bundle exec rake spec
